services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - GENERIC_TIMEZONE="Europe/Berlin"
      - TZ="Europe/Berlin"
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./.local/n8n-home:/home/node/.n8n
      - ./.local/n8n-files:/files