version: '3'

vars:
  CURRENT_DIR: { sh: pwd }
  KUBECONFIG_MRS: $HOME/.kube/mrs-k0s.conf
  NAMESPACE: operator-system

dotenv: [.env]

tasks:
  bootup:
    desc: Boot up the operator in local k0s cluster
    silent: true
    cmds:
      - docker-compose -f {{.CURRENT_DIR}}/docker-compose.yaml up -d
      - echo "n8n ready in http://localhost:5678"

  teardown:
    desc: Tear down the operator and k0s cluster
    silent: true
    cmds:
      - docker-compose -f {{.CURRENT_DIR}}/docker-compose.yaml down -v

  run:
    desc: Run llm-operator
    cmds:
      - uv run kopf run main.py --all-namespaces --liveness http://0.0.0.0:8080/healthz --standalone

  latest-tag:
    desc: Show latest git tag
    silent: true
    cmds:
      - git describe --tags `git rev-list --tags --max-count=1`

  crd-cleanup:
    desc: Delete CRDs and their resources
    silent: true
    vars:
      # CRDs with corresponding resource types
      CRDS: >-
        litellmkeys:litellmkey
        litellmmodels:litellmmodel
        ollamamodels:ollamamodel
        n8nadminusers:n8nadminuser
        n8napikeys:n8napikey
        openwebuibanners:openwebuibanner
        openwebuichannels:openwebuichannel
      CRD_DOMAIN: ops.veitosiander.de
      PATCH_FINALIZERS: '{"metadata":{"finalizers":[]}}'
    cmds:
      # Patch CRD finalizers
      - |
        for crd_pair in {{.CRDS}}; do
          crd_name="${crd_pair%%:*}"
          echo "Patching CRD ${crd_name}.{{.CRD_DOMAIN}}..."
          kubectl patch crd "${crd_name}.{{.CRD_DOMAIN}}" \
            -p '{{.PATCH_FINALIZERS}}' --type=merge 2>/dev/null || true
        done
      # Patch resource instance finalizers
      - |
        for crd_pair in {{.CRDS}}; do
          resource_type="${crd_pair##*:}"
          echo "Patching all ${resource_type} resources..."
          kubectl patch "${resource_type}" --all \
            -p '{{.PATCH_FINALIZERS}}' --type=merge 2>/dev/null || true
        done
      # Delete all resource instances
      - |
        for crd_pair in {{.CRDS}}; do
          resource_type="${crd_pair##*:}"
          echo "Deleting all ${resource_type} resources..."
          kubectl delete "${resource_type}" --all --wait=false 2>/dev/null || true
        done
      # Delete CRDs with resources
      - |
        for crd_pair in {{.CRDS}}; do
          crd_name="${crd_pair%%:*}"
          echo "Deleting CRD ${crd_name}.{{.CRD_DOMAIN}}..."
          kubectl delete crd "${crd_name}.{{.CRD_DOMAIN}}" --wait=false 2>/dev/null || true
        done
      - echo "CRD cleanup completed."

  leaks:
    desc: Try searching for commited secrets etc
    cmds:
      - trufflehog filesystem .
      - gitleaks git -v

  tag:
    desc: git tag the current release
    cmds:
      - git tag $(svu next) || true
      - git push origin $(svu current)
