version: '3'

vars:
  CURRENT_DIR: { sh: pwd }
  KUBECONFIG_MRS: $HOME/.kube/mrs-k0s.conf
  NAMESPACE: operator-system

dotenv: [.env]

tasks:
  run:
    desc: Run llm-operator
    env:
      LLM_OPERATOR_PLUGINS: "litellm_key,litellm_model,ollama_model"
    cmds:
      - uv run kopf run main.py --all-namespaces --liveness http://0.0.0.0:8080/healthz --standalone

  latest-tag:
    desc: Show latest git tag
    silent: true
    cmds:
      - git describe --tags `git rev-list --tags --max-count=1`

  delete-crds:
    desc: Delete CRDs
    silent: true
    cmds:
      - kubectl delete crd litellmkeys.ops.veitosiander.de || true
      - kubectl delete crd litellmmodels.ops.veitosiander.de || true
      - kubectl delete crd ollamamodels.ops.veitosiander.de || true

  leaks:
    desc: Try searching for commited secrets etc
    cmds:
      - trufflehog filesystem .
      - gitleaks git -v

  tag:
    desc: git tag the current release
    cmds:
      - git tag $(svu next) || true
      - git push origin $(svu current)