version: '3'

vars:
  CURRENT_DIR: { sh: pwd }
  KUBECONFIG_MRS: $HOME/.kube/mrs-k0s.conf
  NAMESPACE: operator-system

dotenv: [.env]

tasks:
  bootup:
    desc: Boot up the operator in local k0s cluster
    silent: true
    cmds:
      - docker-compose -f {{.CURRENT_DIR}}/docker-compose.yaml up -d
      - echo "n8n ready in http://localhost:5678"

  teardown:
    desc: Tear down the operator and k0s cluster
    silent: true
    cmds:
      - docker-compose -f {{.CURRENT_DIR}}/docker-compose.yaml down -v

  run:
    desc: Run llm-operator
    env:
      LLM_OPERATOR_PLUGINS: "n8n_admin_user"
    cmds:
      - uv run kopf run main.py --all-namespaces --liveness http://0.0.0.0:8080/healthz --standalone

  latest-tag:
    desc: Show latest git tag
    silent: true
    cmds:
      - git describe --tags `git rev-list --tags --max-count=1`

  crd-cleanup:
    desc: Delete CRDs
    silent: true
    cmds:
      - kubectl patch crd litellmkeys.ops.veitosiander.de -p '{"metadata":{"finalizers":[]}}' --type=merge || true
      - kubectl patch crd litellmmodels.ops.veitosiander.de -p '{"metadata":{"finalizers":[]}}' --type=merge || true
      - kubectl patch crd ollamamodels.ops.veitosiander.de -p '{"metadata":{"finalizers":[]}}' --type=merge || true
      - kubectl patch crd n8nadminusers.ops.veitosiander.de -p '{"metadata":{"finalizers":[]}}' --type=merge || true
      - kubectl patch crd n8napikeys.ops.veitosiander.de -p '{"metadata":{"finalizers":[]}}' --type=merge || true
      - kubectl patch litellmkey --all -p '{"metadata":{"finalizers":[]}}' --type=merge || true
      - kubectl patch litellmmodel --all -p '{"metadata":{"finalizers":[]}}' --type=merge || true
      - kubectl patch ollamamodel --all -p '{"metadata":{"finalizers":[]}}' --type=merge || true
      - kubectl patch n8nadminuser --all -p '{"metadata":{"finalizers":[]}}' --type=merge || true
      - kubectl patch n8napikey --all -p '{"metadata":{"finalizers":[]}}' --type=merge || true
      - kubectl delete litellmkey --all || true
      - kubectl delete litellmmodel --all || true
      - kubectl delete ollamamodel --all || true
      - kubectl delete n8nadminuser --all || true
      - kubectl delete n8napikey --all || true
      - kubectl delete crd litellmkeys.ops.veitosiander.de || true
      - kubectl delete crd litellmmodels.ops.veitosiander.de || true
      - kubectl delete crd ollamamodels.ops.veitosiander.de || true
      - kubectl delete crd n8nadminusers.ops.veitosiander.de || true
      - kubectl delete crd n8napikeys.ops.veitosiander.de || true

  leaks:
    desc: Try searching for commited secrets etc
    cmds:
      - trufflehog filesystem .
      - gitleaks git -v

  tag:
    desc: git tag the current release
    cmds:
      - git tag $(svu next) || true
      - git push origin $(svu current)