apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "helm.fullname" . }}-namespaced
  labels:
    {{- include "helm.labels" . | nindent 4 }}
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [ops.veitosiander.de]
    resources: [litellmkeys]
    verbs: [list, watch, patch, get, create, update, delete, deletecollection]

  # Application: other resources it produces and manipulates in the namespace.
  - apiGroups: [""]
    resources: [pods, services, configmaps, secrets, persistentvolumeclaims, endpoints]
    verbs: [get, list, watch, create, update, patch, delete, deletecollection]

  # Workload resources in namespace
  - apiGroups: [apps]
    resources: [deployments, replicasets, daemonsets, statefulsets]
    verbs: [get, list, watch, create, update, patch, delete, deletecollection]

  # Batch resources in namespace
  - apiGroups: [batch]
    resources: [jobs, cronjobs]
    verbs: [get, list, watch, create, update, patch, delete, deletecollection]

  # Extensions resources in namespace
  - apiGroups: [extensions]
    resources: [deployments, replicasets, ingresses, daemonsets]
    verbs: [get, list, watch, create, update, patch, delete, deletecollection]

  # Networking resources in namespace
  - apiGroups: [networking.k8s.io]
    resources: [ingresses, networkpolicies]
    verbs: [get, list, watch, create, update, patch, delete, deletecollection]

  # RBAC resources in namespace
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [roles, rolebindings]
    verbs: [get, list, watch, create, update, patch, delete, deletecollection]

  # Service accounts in namespace
  - apiGroups: [""]
    resources: [serviceaccounts]
    verbs: [get, list, watch, create, update, patch, delete, deletecollection]

  # Autoscaling resources in namespace
  - apiGroups: [autoscaling]
    resources: [horizontalpodautoscalers]
    verbs: [get, list, watch, create, update, patch, delete, deletecollection]

  # Policy resources in namespace
  - apiGroups: [policy]
    resources: [poddisruptionbudgets]
    verbs: [get, list, watch, create, update, patch, delete, deletecollection]

  # Monitoring resources in namespace
  - apiGroups: [monitoring.coreos.com]
    resources: [servicemonitors, prometheusrules, podmonitors]
    verbs: [get, list, watch, create, update, patch, delete, deletecollection]

  # Certificate management in namespace
  - apiGroups: [cert-manager.io]
    resources: [certificates, certificaterequests, issuers]
    verbs: [get, list, watch, create, update, patch, delete, deletecollection]

  # Resource status updates in namespace
  - apiGroups: [""]
    resources: [pods/status, services/status]
    verbs: [get, update, patch]
  - apiGroups: [apps]
    resources: [deployments/status, replicasets/status, daemonsets/status, statefulsets/status]
    verbs: [get, update, patch]
  - apiGroups: [extensions]
    resources: [deployments/status, replicasets/status, daemonsets/status]
    verbs: [get, update, patch]

  # Lease resources for leader election
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]
