apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "helm.fullname" . }}-namespaced
  labels:
    {{- include "helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "helm.fullname" . }}-namespaced
subjects:
  - kind: ServiceAccount
    name: {{ include "helm.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
